DapperProject/Controllers/GorevliController.cs
using System;
using DapperProject.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data;
using System.Data.SqlClient;

namespace DapperProject.Controllers
{
    public class GorevliController : Controller
    {
        // GET: Gorevli
        public ActionResult Index()
        {
            return View(DP.Listeleme<GorevliModel>("ViewGorevliAll"));
        }
        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@GorevliNo", id);
                return View(DP.Listeleme<GorevliModel>("ViewGorevliByNo", param).FirstOrDefault<GorevliModel>());
            }
        }
        [HttpPost]
        public ActionResult EY(GorevliModel gorevli)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@GorevliNo",gorevli.GorevliNo);
            param.Add("@AdSoyad",gorevli.AdSoyad);
            param.Add("@Yas",gorevli.Yas);
            param.Add("@Telefon",gorevli.Telefon);
            param.Add("@MesaiDurum",gorevli.MesaiDurum);
            param.Add("@Maas",gorevli.Maas);
            param.Add("@Prim",gorevli.Prim);
            param.Add("@SalonNo",gorevli.SalonNo);
            DP.ExecuteReturn("GorevliEY", param);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id=0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@GorevliNo", id);
            DP.ExecuteReturn("GorevliDel", param); 
            return RedirectToAction("Index");
        }
    }
}

DapperProject/Controllers/HizmetlerController.cs
using DapperProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data;
using System.Data.SqlClient;

namespace DapperProject.Controllers
{
    public class HizmetlerController : Controller
    {
        // GET: Hizmetler
        public ActionResult Index()
        {
            return View(DP.Listeleme<HizmetlerModel>("ViewHizmetlerAll"));
        }
        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@HizmetNo", id);
                return View(DP.Listeleme<HizmetlerModel>("ViewHizmetlerByNo", param).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult EY(HizmetlerModel hizmetler)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@HizmetNo", hizmetler.HizmetNo);
            param.Add("@HizmetAdi", hizmetler.HizmetAdi);
            param.Add("@HizmetAmaci", hizmetler.HizmetAmaci);
            param.Add("@HizmetTutar", hizmetler.HizmetTutar);
            param.Add("@OdemeTuru", hizmetler.OdemeTuru);
            param.Add("@GorevliNo", hizmetler.GorevliNo);
            DP.ExecuteReturn("HizmetlerEY", param);
            return RedirectToAction("Index");
        }
        public ActionResult Delete (int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@HizmetNo", id);
            DP.ExecuteReturn("HizmetlerDel", param);
            return RedirectToAction("Index");
        }
    }
}

DapperProject/Controllers/MalzemeController.cs
using DapperProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data;
using System.Data.SqlClient;

namespace DapperProject.Controllers
{
    public class MalzemeController : Controller
    {
        // GET: Malzeme
        public ActionResult Index()
        {
            return View(DP.Listeleme<MalzemeModel>("ViewMalzemeAll"));
        }
        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@MalzemeNo", id);
                return View(DP.Listeleme<MalzemeModel>("ViewMalzemeByNo", param).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult EY(MalzemeModel malzeme)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@MalzemeNo", malzeme.MalzemeNo);
            param.Add("@MalzemeAdi", malzeme.MalzemeAdi);
            param.Add("@MalzemeTutar", malzeme.MalzemeTutar);
            param.Add("@HizmetNo", malzeme.HizmetNo);
            param.Add("@Fayda", malzeme.Fayda);
            param.Add("@Aciklama", malzeme.Aciklama);
            DP.ExecuteReturn("MalzemeEY", param);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@MalzemeNo", id);
            DP.ExecuteReturn("MalzemeDel", param);
            return RedirectToAction("Index");
        }
    }
}

DapperProject/Controllers/SalonlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using Dapper;
using DapperProject.Models;

namespace DapperProject.Controllers
{
    public class SalonlarController : Controller
    {
        // GET: Salonlar
        public ActionResult Index()
        {
            return View(DP.Listeleme<SalonlarModel>("ViewSalonlarAll"));
        }
        public ActionResult EY(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@SalonNo", id);
                return View(DP.Listeleme<SalonlarModel>("ViewSalonlarByNo", param).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult EY(SalonlarModel salonlar)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@SalonNo", salonlar.SalonNo);
            param.Add("@SalonAdi", salonlar.SalonAdi);
            param.Add("@SalonKapiNo", salonlar.SalonKapiNo);
            param.Add("@YapilanIslem", salonlar.YapilanIslem);
            param.Add("@IslemSayisi", salonlar.IslemSayisi);
            DP.ExecuteReturn("SalonlarEY", param);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@SalonNo", id);
            DP.ExecuteReturn("SalonlarDel", param);
            return RedirectToAction("Index");
        }
    }
}

DapperProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Admin Page</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/admintemplate/assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/admintemplate/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light">Admin Page</div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Home")">Home Page</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Gorevli")">Customers</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Hizmetler")">Services</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Salonlar")">Salons</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Malzeme")">Materials</a>

            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            @*<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="@Url.Action("Index","Home")">Return To Website</a>
                                    <a class="dropdown-item" href="@Url.Action("Logout","Home")">Logout</a>
                                </div>
                            </li>*@
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/admintemplate/js/scripts.js"></script>
</body>
</html>

DapperProject/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Admin Page</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/admintemplate/assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/admintemplate/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light">Admin Page</div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Home")">Home Page</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Branches")">Branches</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Personel")">Personels</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Books")">Books</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index","Customer")">Customers</a>

            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="@Url.Action("Index","Home")">Return To Website</a>
                                    <a class="dropdown-item" href="@Url.Action("Logout","Home")">Logout</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/admintemplate/js/scripts.js"></script>
</body>
</html>